### ISSUE TITLE
Support for multiple streaming

### ISSUE THREAD

**Issue by yashkan27** [KnugiHK/rtmplite3#1]
Hi,
First of all, thank you for the repo. I used it to get streaming from my mobile.
I was thinking of how to stream for multiple streaming links. When I try multiple streaming an exception occurred.
Can you guide me on this?
Thanks

**Comment by KnugiHK** [comment]
Do you mean streaming multiple feeds to the server?
If so, no setting/programming need to be done. What you need is just stream them with different stream keys. (At least it's works for me)

If you need more assistants from me, no problem! I will try. Just start the server with option "-d" to show the details of the server, and post the output of the exception in this issue.
